FROM postgres:14.9-alpine

WORKDIR /opt

RUN apk add --no-cache supervisor

COPY . .

RUN cp /opt/cron/db_backup.sh /etc/periodic/hourly/db_backup \
    && chmod a+x /etc/periodic/hourly/db_backup \
    && mkdir /etc/supervisor.d \
    && cp /opt/cron/postgres_cron.ini /etc/supervisor.d/postgres_cron.ini

ENTRYPOINT ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]